version: '3.8'
services:
  server:
    container_name: project_2_server
    image: arichards98/project_2_server
    build: ./server
    deploy:
      replicas: 2
    environment:
      DATABASE_URI: ${DATABASE_URI}
    ports:
    - published: 5000
      target: 5000 
        
  species_api:
    container_name: species_api
    image: arichards98/species_api:new
    build: ./species_api
    deploy:
      replicas: 2
  
  class_api:
    container_name: class_api
    image: arichards98/class_api:new
    build: ./class_api
    deploy:
      replicas: 2
  
  stats_api:
    container_name: stats_api
    image: arichards98/stats_api:new
    build: ./stats_api
    deploy:
      replicas: 2

  nginx:
    image: nginx:latest
    deploy:
      replicas: 2
    ports:
    - target: 80
      published: 80
      protocol: tcp
    volumes:
    - type: bind
      source: ./nginx.conf
      target: /etc/nginx/nginx.conf
